filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
releases:
- chart: dev/jx3-react-quickstart
  version: 0.0.1
  name: jx3-react-quickstart
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
